[theme]
background = "#FFFFFF"
primary = "#000000"
secondary = "#737373"
title = "#1E51D7"
playing = "#32CD32"
playing_selected = "#32CD32"
playing_bg = "#F8F4F4"
highlight =  "#1E51D7"
highlight_bg = "#B9B6B6"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#32CD32"
statusbar_bg = "#B4BAB7"
cmdline = "#FFFFFF"
cmdline_bg = "#444444"
[track_format]
left = "%title - %album"
center = "%artists"
right = "%saved %duration"
