
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Er tilpassa flere ganger og splitta i filer som ligger i undermappa modules

------------------
---- MONITORS i monitors.lua
------------------

require("modules.monitors")

-----------------------------------------------------
--- Autostart og ENVIRONMENT i grunnleggende.lua
------------------------------------------------------

require("modules.grunnleggende")

---------------------
---- MY PROGRAMS ----
---------------------

-- Viktige programmer får en variabel.
terminal    = "kitty"
fileManager = "thunar"
menu        = "rofi -show drun"

-----------------------
----- PERMISSIONS -----
-----------------------

-- Har ikke konfigurert med dette. Forslaget ligger i prerm.lua i modules


-----------------------
---- LOOK AND FEEL ----
-----------------------

require("modules.utseende")

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

require("modules.mus_tastatur")

---------------------
---- KEYBINDINGS ----
---------------------

mainMod = "SUPER" -- Sets "Windows" key as main modifier
 require("modules.bindinger")


-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
--[[
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("audacity"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("blueman-manager"))
]]
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

require("modules.vindu_flater")


local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

-- Velge layout på workspace
hl.bind("SUPER + tab", function ()
    local layouts     = { "scrolling", "dwindle", "master", "monocle" }
    local workspace   = hl.get_active_workspace()
	if hl.get_active_special_workspace() then
		workspace = hl.get_active_special_workspace()
	end

    local next_layout = "dwindle"

    if not workspace then
        return
    end

    for i = 1, #layouts do
        if layouts[i] == workspace.tiled_layout then
            local next_layout_idx = (i % #layouts) + 1
            next_layout = layouts[next_layout_idx]
            break
        end
    end

	if workspace.special then
		hl.workspace_rule({ workspace = tostring(workspace.name), layout = next_layout })
	else
		hl.workspace_rule({ workspace = tostring(workspace.id), layout = next_layout })
	end
end)


-- Blar i vinduer med piltaster

hl.bind("ALT + right", function()
    local ws = hl.get_active_workspace()
    if ws and ws.tiled_layout == "monocle" then
        hl.dispatch(hl.dsp.layout("cyclenext"))
    else
        hl.dispatch(hl.dsp.focus({ direction = "down" }))
    end
end, { description = "Cycle next window or focus down" })

hl.bind("ALT + left", function()
    local ws = hl.get_active_workspace()
    if ws and ws.tiled_layout == "monocle" then
        hl.dispatch(hl.dsp.layout("cycleprev"))
    else
        hl.dispatch(hl.dsp.focus({ direction = "up" }))
    end
end, { description = "Cycle previous window or focus up" })

---------------------------------
--- PLUGINS
---------------------------------
-- Ensure the plugin section is safely evaluated if loaded
-- hyprbars er konfigurert i plugins.lua
require("modules.plugins")
